baseURL = 'https://www.maoserr.com/'
title = '@Maoserr'

author = "Mao Yu"
copyright = "Mao Yu"
paginate = 10
languageCode = "en"
theme = "tailwind"

[params]
# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"
subtitle = 'Casual Code'

[params.header]
logo = "images/logo.png"

[params.giscus]
enabled = true
repo = "maoserr/maoserr.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkyMDI1NDQxNQ=="
category = "Announcements"
categoryID = "DIC_kwDOATUOz84Cnh54"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
lang = "en"

[[params.social_media.items]]
enabled = true
title = 'LinkedIn'
icon = 'brand-linkedin'
link = 'https://www.linkedin.com/in/maoserr/'

[[params.social_media.items]]
enabled = true
title = 'Github'
icon = 'brand-github'
link = 'https://github.com/maoserr'

[params.footer]
since = 2023
poweredby = false

#[[menu.main]]
#identifier = "proja"
#name = "Project A"
#URL = "https://maoserr.com/project_a_release"
#weight = 1

[menu]
[[menu.main]]
identifier = "post"
name = "Post"
pageRef = "/post"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 0



[taxonomies]
category = "categories"
tag = "tags"
series = "series"


