baseURL = 'https://www.maoserr.com/'
languageCode = 'en-us'
title = '@Maoserr'
paginate = 3
theme = 'hugotex'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Params.Author]
name = "Mao Yu"
abstract = """
  Casual code cook. There's nothing to see here.
  """

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "paraiso-dark" # syntax highlighting style

[Params]
darkmode = true
